# Setup
title:        Bingyu Zhou's Blog
tagline:      When AI encounters Robotics and Control
baseurl:      ""
paginate:     3
locale:       "en"
github_username: BingyuZhou
timezone: Europe/Berlin

# About/contact
author:
  name:       Bingyu Zhou
  url:        https://www.linkedin.com/in/bingyuzhou/
  

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
kramdon:
  math_engine: mathjax

theme: jekyll-theme-cayman