# Setup
title:        Bingyu Zhou's Blog
tagline:      When AI encounters Robotics and Control
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Bingyu Zhou
  url:        https://www.linkedin.com/in/bingyuzhou/

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
